# sonar-project.properties
sonar.projectKey=medical-chatbot
sonar.projectName=medical-chatbot
sonar.sources=.
sonar.exclusions=**/venv/**,**/.git/**,**/__pycache__/**,**/*.pyc,**/data/**,**/models/**,**/static/**,**/templates/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.branch.name=
sonar.pullrequest.key=
sonar.pullrequest.branch=
sonar.pullrequest.base=
